[build]
builder = "dockerfile"
dockerfilePath = "src/Flygio/Dockerfile"
watchPatterns = ["src/**"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
